language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - ~/.composer/cache

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    recipients:
      - daison12006013@gmail.com
